### ISSUE TITLE
你好，树不支持横向滚动条？

### ISSUE THREAD

**Issue by qingyusuxi** [hsiangleev/layuiExtend#10]
[``](url)
![image](https://user-images.githubusercontent.com/27907939/49501342-948b7c00-f8ad-11e8-8276-b548a9455751.png)
能否出现横向滚动条，谢谢

**Comment by hsiangleev** [comment]
@qingyusuxi 这个可以自己设置，可以给eleTree设置一个最小宽度 min-height，然后外面的容器设置 overflow-x: scroll;

**Comment by qingyusuxi** [comment]
谢谢！已解决。
