### ISSUE TITLE
eletree的defaultchecked数据上百后会出现崩溃

### ISSUE THREAD

**Issue by FavorPan** [hsiangleev/layuiExtend#14]
当defaultCheckedKeys的数据上百之后，tree会一直卡死，然后最后页面崩溃

**Comment by hsiangleev** [comment]
@FavorPan 可以发我一份数据吗，这个数据太多，不太好测试

**Comment by FavorPan** [comment]
我这边是要渲染六千条数据，然后默认选中当中的一百多条数据就会卡死...

**Comment by FavorPan** [comment]
但是用你10/27的eletree却是可以默认checked一千多条

**Comment by FavorPan** [comment]
我现在是自己处理数据，把我想要默认选中的对象都加上checked：true这样就可以实现，因为新版的eletree的data没有这个属性所以我就放弃了新版；所以我建议新版的eletree还是保留checked：true比较好

**Comment by hsiangleev** [comment]
@FavorPan 新版本已经加上checked：true了

**Comment by FavorPan** [comment]
Thank you.
