### ISSUE TITLE
在children中加上checked之后，父级的checkbox没有选中

### ISSUE THREAD

**Issue by 1260328762** [hsiangleev/layuiExtend#18]

**Comment by hsiangleev** [comment]
@1260328762 我测试的可以选中啊

**Comment by 1260328762** [comment]
手动点击的选中的话，子复选框和父复选框都可以选中，当数据从后台传过来的时候就会出现，只有子复选框选中，父复选框没反应

**Comment by 1260328762** [comment]
URL
https://shantuiwangluo-test.oss-cn-hangzhou.aliyuncs.com/_20190103104021.png


就像图片这种

**Comment by hsiangleev** [comment]
@1260328762 我知道原因了，是因为默认的renderAfterExpand是true，每次只在点击的时候才加载dom，忘了考虑这一点，我改一下

**Comment by hsiangleev** [comment]
@1260328762 我提交了，现在是当你点开子层，如果子层有选中，才会去选中父层，并不是一开始就选中父层，如果这个需求不满足你，你可以把renderAfterExpand参数设为false

**Comment by 1260328762** [comment]
可以了，很好用，thank you

**Comment by hsiangleev** [comment]
@1260328762 不客气，感谢指正的问题

**Comment by 1260328762** [comment]
我又来了，我发现当tree的内容变多的时候，下面的内容会被遮挡住，就像这两张图片，
https://shantuiwangluo-test.oss-cn-hangzhou.aliyuncs.com/20190104104538.png
https://shantuiwangluo-test.oss-cn-hangzhou.aliyuncs.com/20190104104612.png

**Comment by 1260328762** [comment]
还有就是当我点击下面的叶子节点的时候浏览器会卡死，然后报下面的错误
https://shantuiwangluo-test.oss-cn-hangzhou.aliyuncs.com/20190104110125.png

**Comment by hsiangleev** [comment]
@1260328762 遮住应该是有css样式overflow:hidden的样式，去掉应该就可以了，浏览器卡死目前还没遇到过，你用的是ie浏览器吗，卡死的触发条件是什么，就只是内容多的时候出现吗

**Comment by 1260328762** [comment]
我用的是谷歌浏览器，都会卡，就是每次点击里面的叶子节点的时候都会卡住，就像图中的角色列表，分配权限那些选项，但是点击旁边的checkbox就不会出现这种情况，我刚刚把expandOnClickNode:false加上就好了
这张图片是点击卡死的时候，浏览器也关不上，必须在进程中杀死才行
http://shantuiwangluo-test.oss-cn-hangzhou.aliyuncs.com/1546587367399.png
然后过了很长时间，就会自动冒出一个deuggger界面
http://shantuiwangluo-test.oss-cn-hangzhou.aliyuncs.com/1546586937468.png

**Comment by hsiangleev** [comment]
@1260328762 你的id是不是有重名的，又可能是id重名的原因

**Comment by 1260328762** [comment]
我的父节点的id都为null，不会是这个原因把

**Comment by hsiangleev** [comment]
@1260328762 现在的id是必须要的，因为里面的东西都是用这个字段来区别的，所有如果id如果出现一样的话，有可能会出现死循环

**Comment by 1260328762** [comment]
我刚试了下都加上id了，还是不行，是不是父级的id和子级的id都不能重复，这是我的数据

{
	"code": 0,
	"data": [{
		"id": 4,
		"label": "系统管理",
		"checked": false,
		"children": [{
			"id": 1,
			"label": "用户管理",
			"checked": false,
			"children": [{
				"id": 1,
				"label": "添加用户",
				"checked": false,
				"children": null
			}, {
				"id": 3,
				"label": "更新用户",
				"checked": false,
				"children": null
			}, {
				"id": 6,
				"label": "用户添加页面",
				"checked": false,
				"children": null
			}, {
				"id": 7,
				"label": "用户编辑页面",
				"checked": false,
				"children": null
			}, {
				"id": 8,
				"label": "用户列表",
				"checked": true,
				"children": null
			}, {
				"id": 9,
				"label": "用户管理页面",
				"checked": true,
				"children": null
			}, {
				"id": 19,
				"label": "分配角色",
				"checked": false,
				"children": null
			}]
		}, {
			"id": 5,
			"label": "登陆日志",
			"checked": false,
			"children": [{
				"id": 4,
				"label": "日志列表",
				"checked": false,
				"children": null
			}]
		}, {
			"id": 8,
			"label": "角色管理",
			"checked": false,
			"children": [{
				"id": 11,
				"label": "角色管理页面",
				"checked": false,
				"children": null
			}, {
				"id": 12,
				"label": "角色列表",
				"checked": false,
				"children": null
			}, {
				"id": 13,
				"label": "分配权限",
				"checked": false,
				"children": null
			}, {
				"id": 14,
				"label": "权限列表",
				"checked": false,
				"children": null
			}, {
				"id": 15,
				"label": "权限管理界面",
				"checked": false,
				"children": null
			}, {
				"id": 16,
				"label": "添加角色",
				"checked": false,
				"children": null
			}, {
				"id": 17,
				"label": "删除角色",
				"checked": false,
				"children": null
			}]
		}]
	}, {
		"id": 9,
		"label": "首页",
		"checked": false,
		"children": [{
			"id": 10,
			"label": "后台首页",
			"checked": false,
			"children": [{
				"id": 18,
				"label": "欢迎页",
				"checked": true,
				"children": null
			}]
		}]
	}]
}

**Comment by hsiangleev** [comment]
@1260328762 肯定是所有的id都不能重复

**Comment by 1260328762** [comment]
那我知道了，谢谢
