### ISSUE TITLE
后台返回数据只需要选中父级，渲染之后连子级也被选中了，比如只选广东就会连带广州也会选中

### ISSUE THREAD

**Issue by bb168ll** [hsiangleev/layuiExtend#19]
如下后台返回数据，只选择了广东、深圳，但是南山和广州都被选中了

[{
	"id": "1",
	"label": "分公司",
	"spread": true,
	"children": [{
		"id": "25",
		"label": "广东",
		"checked": true,
		"spread": true,
		"children": [{
			"id": "26",
			"label": "深圳",
			"checked": true,
			"spread": true,
			"children": [{
				"id": "31",
				"label": "南山",
				"spread": true
			}]
		}, {
			"id": "30",
			"label": "广州",
			"spread": true
		}]
	}, {
		"id": "27",
		"label": "湖南",
		"spread": true
	}]
}]

**Comment by hsiangleev** [comment]
@bb168ll 可以使用参数 checkStrictly 控制，使父子不关联
