### ISSUE TITLE
我来提BUG啦，鼠标右键出现的菜单栏 没有计算padding/margin?

### ISSUE THREAD

**Issue by hugselina** [hsiangleev/layuiExtend#2]
如题 
我外部是用layui-fluid包裹 然后在这一层加了一个padding-left = 200 px;  因为我同时使用了 顶部导航栏 与侧边导航栏 顶部导航栏 高60px  ， 侧边导航栏 宽200px ，于是在引用eleTree以后 在对应的菜单 右键  出现的菜单 向下偏移60px （目测） 向右偏移200px（目测 没有量 不过90%妥了），导致不能点选右键的菜单栏（新增 、 删除 、编辑 等等 都不能选）， 去看了鼠标右键的rightClickMenu()函数，一脸懵- -！求解决~

**Comment by hsiangleev** [comment]
@hugselina 感谢你的反馈，本来应该是直接把右键菜单追加document.body上面的，我以为改过了，一直没注意到，已经提交上去了，把231行的 `$(self.elem).after(self.treeMenu);`改为 `$(document.body).after(self.treeMenu);`就可以了，不好意思，代码写的有点乱，一直没有整理
