### ISSUE TITLE
授权问题

### ISSUE THREAD

**Issue by weathon** [hsiangleev/layuiExtend#20]
作者您好！我对你这个项目十分感兴趣，想用字啊我的商业项目上，请问是否允许？是否需要标注原作者？
谢谢诶！

**Comment by hsiangleev** [comment]
@weathon 感谢您的认可，我新加入了 MIT 协议

**Comment by weathon** [comment]
谢谢

**Comment by weathon** [comment]
> @weathon 感谢您的认可，我新加入了 MIT 协议

请问MIT就是可以不标明作者使用吗？在我的程序的开源许可证页面要写什么东西吗？
谢谢

**Comment by hsiangleev** [comment]
@weathon 我对这个也不是太清楚，layui用的也是这个协议，跟layui一样使用就可以了吧

**Comment by weathon** [comment]
好的，谢谢
