### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by weathon** [hsiangleev/layuiExtend#21]
请问有详细一点的文档吗？比如要倒入那些文件，如何使用右键菜单，如何动态添加节点，如何导出节点。谢谢

**Comment by hsiangleev** [comment]
@weathon [文档链接](http://118.178.226.143:9090/urp/layuiExtend/eleTree/)，这个就相当于layui的扩展模块，按照layui的扩展模块引入就行

**Comment by weathon** [comment]
> @weathon [文档链接](http://118.178.226.143:9090/urp/layuiExtend/eleTree/)，这个就相当于layui的扩展模块，按照layui的扩展模块引入就行
@hsiangleev 请问需要引入独有的js吗？还有就是demo的右键菜单很好，请问要怎么做？谢谢

**Comment by weathon** [comment]
@hsiangleev

**Comment by weathon** [comment]
好的谢谢，emmmm，还有就是动态添加完节点（用右键菜单）怎样导出呢？以及支持自定义美化吗？毕竟官方的tree已经没用了，现在eletree不符合客户要求（虽然我觉得很好了）
麻烦您了

**Comment by hsiangleev** [comment]
@weathon 导出是什么意思，目前不支持自定义美化，因为使用的风格与layui的整体风格相似

**Comment by weathon** [comment]
就是用户右键添加了节点之后，如何把新的树传递到服务器储存？

**Comment by weathon** [comment]
谢谢

**Comment by weathon** [comment]
@hsiangleev

**Comment by weathon** [comment]
效率真高👍👍👍
谢谢了
这个可以返回一个完整的树吗？因为我觉得返回单个节点有点麻烦

**Comment by hsiangleev** [comment]
@weathon 以前返回的是整个树，但是数据太大感觉不太合理，就返回单个了

**Comment by weathon** [comment]
有些时候数据量其实不大，而且不只有添加自节点，还有删除啊，改名啊，添加平行节点啊之类的

**Comment by weathon** [comment]
麻烦您了，可以加一个属性直接返回json或者字符串吗？
当然方法也可以

**Comment by weathon** [comment]
我这个项目年前才要交，还有几周

**Comment by hsiangleev** [comment]
@weathon 删除添加修改都有返回单个数据，这个每个人的情况都不同，还是返回单个数据合理些，后面不准备改了，如果需要的话，可以自行添加，大概在1093行左右再添加数据就可以了

**Comment by weathon** [comment]
好的谢谢！

**Comment by hsiangleev** [comment]
@weathon 
![eleTree](https://raw.githubusercontent.com/hsiangleev/layuiExtend/master/images/6CH}Y{3O50PO(5`RP[H3XI2.png)

**Comment by weathon** [comment]
所以这个_self.config.data就是当前的json对吧？我向服务器发送这个然后下次再读这个json渲染是一样的对吧？

**Comment by weathon** [comment]
# 谢谢
# 你是我见过回复最快和细致的作者
👍

**Comment by hsiangleev** [comment]
@weathon 这个是在框架里面改的，你需要在事件里面获取到这个数据 (d.d)，然后传给服务器

**Comment by weathon** [comment]
所以数据变量是d.d?
不怎么写前端，那个冒号没看懂
没事，我自己摸索一下

**Comment by weathon** [comment]
谢谢，我已经解决了

**Comment by weathon** [comment]
@hsiangleev 请问那个1097行是哪个文件的呢？layui的js吗

**Comment by weathon** [comment]
仓库里好像没有eletree的js

**Comment by weathon** [comment]
所以eletree的js不在eletree的文件夹下？而是这个？好的，明白了
https://github.com/hsiangleev/layuiExtend/blob/0df2bf96aa06442a89b8a9152cc1b67f6ce34d3b/layui/lay/mymodules/eleTree.js
那还有什么文件要引入呢
谢谢

**Comment by weathon** [comment]
你这个我看到layui自带了很多moudel，但我的没有，不知道为什么

**Comment by weathon** [comment]
抱歉打扰了，已经解决了😂

**Comment by weathon** [comment]
现在的问题是我找不到你截图的那一行代码，也不知道在哪里用d.d

**Comment by weathon** [comment]
现在已经从js文件里面把_self传出来了，并陈宫调用了data，但返回的是空数组(已经是在渲染之后调用了)

**Comment by weathon** [comment]
难道也要在渲染之后返回码？不可以一开始返回指针吗？算了，我自己摸索吧，不麻烦您了

**Comment by weathon** [comment]
@hsiangleev 
好吧，我说了这么多，总结一下吧，其实就是这个组建内部有没有一个变量是储存当前树结构的，如果有，是什么？
谢谢
麻烦您了

**Comment by weathon** [comment]
我现在只想问一个问题，就是我现在已经创建了一个函数（暴漏，返回在外的），返回data，但似乎还是不行

谢谢
