### ISSUE TITLE
样式错乱

### ISSUE THREAD

**Issue by yggo** [hsiangleev/layuiExtend#22]
![40 c o q603nrpeqrfoz_2s](https://user-images.githubusercontent.com/27994074/52858209-7ae79a00-3164-11e9-8ac4-0a84dba7df4d.png)
如图 使用layuiadmin单页版时 首次打开没问题 下次再打开就图标就乱了

**Comment by weathon** [comment]
代码我看看

**Comment by hsiangleev** [comment]
@3151543536 应该是执行了form.val或其它的form方法，再次渲染了checkbox，可以把树放到form的外面，不要被form包裹

**Comment by TroyBug** [comment]
@hsiangleev 
目前有一个需求是提交表单，点击重置按钮样式就错乱了，如果放到form外面布局和代码上就会变得太复杂
![2019-02-21 163406](https://user-images.githubusercontent.com/9970058/53154816-90dadc00-35f6-11e9-89b8-d844cac13733.jpg)

**Comment by weathon** [comment]
就是放在form里面造成的，现在添加了直接获取树JSON的方法，可以用js提交表单
