### ISSUE TITLE
一个添加子节点的bug

### ISSUE THREAD

**Issue by weathon** [hsiangleev/layuiExtend#23]
假如我开启了右键菜单，然后使用右键菜单在同一个父节点下添加两个子节点，这两个子节点的ID会相同，对后期处理会产生影响。图片为我获取其data属性传递到服务器的结果。
![image](https://user-images.githubusercontent.com/41298844/53048015-5e47ac80-3459-11e9-9041-c14b37a9f782.png)

**Comment by weathon** [comment]
@hsiangleev

**Comment by weathon** [comment]
官方demo没出现，我的项目出现了。

**Comment by weathon** [comment]
现在我这里也复现不了了。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by weathon** [comment]
#21 
复现出来了，问题是这样出现的：
我在一个节点下添加了一个子节点，然后我获取树组建的data属性(上次我向您请教的那个问题)，将这个属性传送到服务端，服务端以文本形式保存JSON，下次使用的时候读取回来，读取回来之后再添加节点就会出现ID冲突的问题。

**Comment by weathon** [comment]
建议：弄一个可以自定义ID的请求位置？或者告诉我怎么做。

**Comment by weathon** [comment]
谢谢

**Comment by hsiangleev** [comment]
@weathon 谢谢，我把默认id改成了时间戳，可以确保不会重复，自定义id默认是支持的，在触发nodeAppend事件的里面，有一个d.setData方法，可以用来自定义数据，可以看下文档

**Comment by weathon** [comment]
好的，谢谢!@hsiangleev

**Comment by weathon** [comment]
时间戳也会有问题，如果批量添加节点还是会重复

**Comment by hsiangleev** [comment]
> 时间戳也会有问题，如果批量添加节点还是会重复

我改了一下，可以了

**Comment by weathon** [comment]
Thanks!
