### ISSUE TITLE
eleTree如何实现全选功能

### ISSUE THREAD

**Issue by TroyBug** [hsiangleev/layuiExtend#25]
请问eleTree要实现全选，有没有内置的方法呢？如果需要自己写代码，应该怎么实现？可否给个思路？非常感谢~

**Comment by hsiangleev** [comment]
可以在后台返回的数据里面加一个checked: true字段

**Comment by TroyBug** [comment]
@hsiangleev 如果要实现全选/取消全选按钮呢？

**Comment by TroyBug** [comment]
@hsiangleev 另外我发现**getChecked**这个方法获取到的数组节点没办法取节点的label值，只能取到id，有什么方法可以取到label值呢？

**Comment by hsiangleev** [comment]
全选现在没增加这个方法，后面可以增加，取消全选有内置方法，获取label的代码今天上午提交了，可以看一下

**Comment by TroyBug** [comment]
@hsiangleev 非常感谢你的帮助☺
