### ISSUE TITLE
id和name

### ISSUE THREAD

**Issue by myto2006** [hsiangleev/layuiExtend#3]
name用于展示，id后台使用，这个是不是要支持下？

**Comment by hsiangleev** [comment]
@myto2006 可以直接在后台数据中加上ID，每次触发事件的时候，返回的数据上面可以拿到当前改的数据位置，或上一级位置
[!eleTree](./images/eleTree-1.png)

**Comment by myto2006** [comment]
![image](https://user-images.githubusercontent.com/16770717/46859986-de259080-ce41-11e8-885d-db5ffa9ab113.png)
使用到了这个css，这个付费的啊

**Comment by hsiangleev** [comment]
@myto2006 非常感谢您的提醒，以前没注意到这个文件，文件夹放错了，已经在修改了

**Comment by myto2006** [comment]
不使用checkbox，我想获取选中的那一个数据，该如何实现？

![image](https://user-images.githubusercontent.com/16770717/46927093-64bab780-d066-11e8-988a-63f56ef47ab2.png)

**Comment by weathon** [comment]
> @myto2006 非常感谢您的提醒，以前没注意到这个文件，文件夹放错了，已经在修改了


现在这个项目已经移除了付费css了吧，不会我做出来了项目然后被发传票吧

**Comment by hsiangleev** [comment]
@weathon 项目本身就没有使用layuiAdmin的东西，只需要一个js和一个css就够了，那个是刚开始创建项目的时候忘记了去除那些文件了

**Comment by weathon** [comment]
请问LPGL协议是什么呢？需要付费吗？

**Comment by weathon** [comment]
不是上面提到的LPPL，是lgpl，你仓库里似乎有几个
（我只是问问而已）
