### ISSUE TITLE
源码里面命名有问题导致了一个错误

### ISSUE THREAD

**Issue by Expre** [hsiangleev/layuiExtend#34]
![image](https://user-images.githubusercontent.com/35752873/56039024-eb2a2a80-5d65-11e9-98cd-d21226e489e2.png)

**Comment by Expre** [comment]
![image](https://user-images.githubusercontent.com/35752873/56039088-157be800-5d66-11e9-8c27-285738fede5d.png)

**Comment by Expre** [comment]
![image](https://user-images.githubusercontent.com/35752873/56039177-42c89600-5d66-11e9-96df-2b1df11896b3.png)

**Comment by Expre** [comment]
其他问题没发现

**Comment by Expre** [comment]
![image](https://user-images.githubusercontent.com/35752873/56039563-1f521b00-5d67-11e9-996f-1648270d6383.png)
强迫症患者有点受不了，这个编译器有213个警告，都是这个没有结束符的。其他的都很牛逼很强大。点赞

**Comment by Expre** [comment]
不可以单选吗？我先取消全部，然后再赋值，出现了一个bug，点击的时候会反复展开合上，最后就是循环好几次。

**Comment by Expre** [comment]
![image](https://user-images.githubusercontent.com/35752873/56043149-41e83200-5d6f-11e9-8387-247b142d2561.png)

**Comment by hsiangleev** [comment]
@Expre 第一张图的报错是怎么触发的，后面的图的一些小问题没怎么在意，影响也不大，那个双等号应该也没什么问题，应该是你编辑器要求使用三等号吧，最后一个问题，对同一个树render之后，如果需要重新渲染树，可以使用reload方法，你render了两次，应该是一些事件没有取消导致的

**Comment by Expre** [comment]
> @Expre 第一张图的报错是怎么触发的，后面的图的一些小问题没怎么在意，影响也不大，那个双等号应该也没什么问题，应该是你编辑器要求使用三等号吧，最后一个问题，对同一个树render之后，如果需要重新渲染树，可以使用reload方法，你render了两次，应该是一些事件没有取消导致的
第一张图报错是展开树后反复点击，报错没影响实际运行，参数命名冲突先改一下。
最后一个问题我看下，谢谢作者。

**Comment by Expre** [comment]
> @Expre 第一张图的报错是怎么触发的，后面的图的一些小问题没怎么在意，影响也不大，那个双等号应该也没什么问题，应该是你编辑器要求使用三等号吧，最后一个问题，对同一个树render之后，如果需要重新渲染树，可以使用reload方法，你render了两次，应该是一些事件没有取消导致的

第一张图报错是展开树后反复点击，报错没影响实际运行，参数命名冲突先改一下。
最后一个问题我看下，谢谢作者。

**Comment by hsiangleev** [comment]
@Expre 我测试的没出现报错，修改已经提交过了。
