### ISSUE TITLE
节点被编辑事件nodeEdi，编辑失败 d.stop()取消编辑无效

### ISSUE THREAD

**Issue by Expre** [hsiangleev/layuiExtend#35]
![image](https://user-images.githubusercontent.com/35752873/56091093-e89e1100-5edc-11e9-93b5-b4e8186b517b.png)

**Comment by Expre** [comment]
是我使用方式不对吗？

**Comment by hsiangleev** [comment]
@Expre 这个是异步操作
![eleTree](https://raw.githubusercontent.com/hsiangleev/layuiExtend/master/images/eleTree-6.png)

**Comment by Expre** [comment]
> @Expre 这个是异步操作
> ![eleTree](https://raw.githubusercontent.com/hsiangleev/layuiExtend/master/images/eleTree-6.png)

好的谢谢，这个地方没看到，不好意思。
