### ISSUE TITLE
搜索有点问题可能是我的问题，帮我看一下

### ISSUE THREAD

**Issue by Expre** [hsiangleev/layuiExtend#36]
![image](https://user-images.githubusercontent.com/35752873/56103219-445fad00-5f64-11e9-8564-83c14c883a5f.png)
在搜索没结果之后，继续输入，输入一个字符会新增一行暂无数据。

**Comment by Expre** [comment]
我的问题，按照文档来。

**Comment by ruiifly** [comment]
+1

**Comment by ruiifly** [comment]
最新代码 并没有修复
