### ISSUE TITLE
分享一个下拉选择样式，layui下拉框复制过来的，炒鸡nice

### ISSUE THREAD

**Issue by Expre** [hsiangleev/layuiExtend#37]
.role {
        display: none;
        position: absolute;
        left: 0;
        top: 42px;
        padding: 5px 0;
        z-index: 899;
        min-width: 100%;
        border: 1px solid #d2d2d2;
        max-height: 300px;
        overflow-y: auto;
        background-color: #fff;
        border-radius: 2px;
        box-shadow:rgba(0,0,0,.12) 0 2px 4px;
        box-sizing: border-box;
    }
![image](https://user-images.githubusercontent.com/35752873/56105841-da99d000-5f70-11e9-9d7a-ef1ced9fb57a.png)

**Comment by weathon** [comment]
Thanks
