### ISSUE TITLE
懒加载怎么实现父级半选

### ISSUE THREAD

**Issue by gedongdong** [hsiangleev/layuiExtend#38]
我的下级数据是懒加载出来的，我能不能定义在下级数据没加载的时候让父级半选状态，否则编辑的时候我看不出来哪个父级下有选中的数据

**Comment by hsiangleev** [comment]
@gedongdong 
你的意思是在展开一级节点获取二级节点数据的时候，顺便拿到三级节点是否有被选中的状态放到二级节点数据吗，
那这样的话会出现一开始一级节点未选中，然后展开二级节点，一级节点便被选中了，
这样的话感觉很突然的感觉吧，就是展开子节点的时候突然选中父节点。

**Comment by gedongdong** [comment]
@hsiangleev 我的意思是在二级没有加载出来的时候先让父级半选，这样我就知道这个父级下有选择的项

**Comment by hsiangleev** [comment]
@gedongdong 好像明白你的意思了，我试了一下好像确实有点问题，是展开子节点的时候，子节点选中了，但是父节点没选中这个意思吧，我看一下

**Comment by gedongdong** [comment]
@hsiangleev 恩恩是的，如果有个属性是设置半选的我觉得就好了，这样数据初始化顶级的时候我可以让顶级半选，用户就知道我下面是选了东西的，不然他们以为在编辑的时候看不见半选以为没有选，而且编辑的时候子集如果很多，没有半选的话不能快速定位到已选择的位置，辛苦啦

**Comment by hsiangleev** [comment]
@gedongdong 我改了一下，提交上来了，但是感觉和你说的还是不是一个问题，我的意思是只有父节点点击完成之后才能确定子节点有没有被选中，然后决定选中父节点

**Comment by gedongdong** [comment]
![image](https://user-images.githubusercontent.com/13677866/56271689-aa4a6100-612b-11e9-83b2-75d076f6f7a7.png)
图里的二级数据是懒加载出来的，其实三级里是有个选中项的，但是到目前为止用户不知道选中的在哪里，如果层级很多一层一层找不太现实，如果数据渲染的时候我渲染了半选那就很明确了

**Comment by hsiangleev** [comment]
@gedongdong 就是可能会出现你给的数据是半选，但是子节点只有一个，即应该是全选这种情况

**Comment by hsiangleev** [comment]
@gedongdong 如果数据量不是很大的话，可以不用懒加载的，那样一开始就把所有数据渲染出来应该可以满足需求

**Comment by hsiangleev** [comment]
@gedongdong 好吧，你这个确实太复杂。。。
