### ISSUE TITLE
setChecked过慢卡死的问题

### ISSUE THREAD

**Issue by loda7023link** [hsiangleev/layuiExtend#39]
我这边的树叶不太复杂，就300来个节点，然后setChecked大概300个时，就很慢，查看代码发现逐个逐个300多个太慢了，然后这个过程大约10秒左右才能完成，一般客户承受不了，而easyui是没这个问题，不知道为什么。能优化一下吗

            arr.forEach(function(val,index) {
                var nodeContent=options.elem.find("[data-"+options.request.key+"='"+val+"']").children(".eleTree-node-content");
                // 如果当前没选中则选中
                if(nodeContent.children(".eleTree-hideen").prop("checked")===false){
                    nodeContent.children(".eleTree-checkbox").trigger("click",["default"]);
                }
            })

**Comment by hsiangleev** [comment]
@loda7023link 谢谢你的反馈，一开始没有考虑大数据量，所有就先简单实现了，现在这个方法已经重写并且提交上去了

**Comment by loda7023link** [comment]
我找到了临时的解决方案，我发现setChecked的时候，当trigger("click")的时候，每次都会触发_self.checkboxRender（在第448行左右），checkboxRender每次执行都会遍历所有节点，这就导致很慢了。

假设我有400个节点，有300个点需要勾选，就遍历循环了120000次了，所以很慢。

现在我暂时注释就好了。
 //_self.checkboxRender();

不过也感谢你的快速反馈。

**Comment by loda7023link** [comment]
用了你最新的js，也可以了，不知道你反馈更新这么快，就知道我就不瞎折腾一个上午了。

非常感谢
