### ISSUE TITLE
建议对eleTree右键菜单可自定义

### ISSUE THREAD

**Issue by wzfxue** [hsiangleev/layuiExtend#40]
如题。

**Comment by hsiangleev** [comment]
@wzfxue 你说的自定义是什么意思，不是太明白

**Comment by wzfxue** [comment]
> @wzfxue 你说的自定义是什么意思，不是太明白

![image](https://user-images.githubusercontent.com/19793076/56856643-7d9b1280-6991-11e9-8740-793d0aa903b3.png)
-- 这一块最好是能够允许自定义。

-- 再就是前天在使用的时候，当数据量超过一定数量非常卡，特别是开启renderAfterExpand，checkStrictly这些选项的时候。（能否将dom结构简化一下，ztree对于大数据量的加载支持比较好是否可参考下。）
-- 还有一个问题是初始化加载之后我勾选父级节点，当不展开子节点的时候，getChecked 是无法获取到子节点数据的。

**Comment by hsiangleev** [comment]
@wzfxue 大数据量我目前没有测试过，现在还会卡吗，还有第二个问题应该是子节点还未渲染，getChecked方法是通过dom节点获取选中的数据的，后面可以改一下

**Comment by hsiangleev** [comment]
还有你说的那个自定义，是对文字的自定义吗，应该不需要吧，每个文字就是代表的功能啊

**Comment by wzfxue** [comment]
卡顿那个问题下午我再测试下之后给你反馈吧。
不是对文字的自定义是对菜单可以增加自定义项（因为在操作上不仅仅是增删改 比如需要一个根据当前选择的节点"加载资源"的菜单项。但是又不想通过节点点击来实现。）

**Comment by hsiangleev** [comment]
@wzfxue 就是说在这个地方加一个插槽之类的，用户可以自己自定义一个功能的意思吗，还有上面的那个getChecked的方法，我想了一下，还是要通过dom获得数据，因为数据上面没有增加dom选中的标记

**Comment by wzfxue** [comment]
对就是这个意思用户自定义项。
然后我试了下renderAfterExpand这个参数看文档中意思是代表即使不展开子节点也渲染dom。但是好像对getChecked上并不起作用。

**Comment by hsiangleev** [comment]
@wzfxue renderAfterExpand意思是页面一开始只加载第一层的数据，点击之后才会加载之后的数据，所以你选中父节点之后，子节点还没有渲染，而getChecked方法是通过dom节点查找数据的，所以出现这个问题，现在的解决方式是把renderAfterExpand设置为false

**Comment by wzfxue** [comment]
前天我就是把renderAfterExpand设置为false了，好像也是没有返回子节点数据。下午我再重新试下之后给你反馈。非常感谢你的解答

**Comment by hsiangleev** [comment]
@wzfxue 好的，谢谢你的意见，上面的那个自定义我考虑一下，应该可以实现

**Comment by wzfxue** [comment]
刚刚又试了下renderAfterExpand设置为false之后getChecked可以返回子节点，卡顿现象也没出现。
有可能是前天试的时候有缓存，没生效

**Comment by hsiangleev** [comment]
@wzfxue 好的，谢谢，还有刚才你说的那个自定义右键菜单已经加上了

**Comment by wzfxue** [comment]
又来麻烦你了，考虑一下对setChecked方法添加一个参数代表是否级联选择。场景是：
假如有树如下：
1
  1-0
  1-1
2
  2-0
  2-1
伪码：setChecked([{id:'1'},{id:'1-0'}]);
这种场景是会把 1,1-0,1-1 全部选中。
相当于将checkStrictly这个参数属性从实例化放到了setChecked方法中。这样是否更合理一些？

-----------------------------
再就是可以考虑增加对list数据的支持（转换），现在是自己将list转换为tree的数据。

**Comment by hsiangleev** [comment]
@wzfxue 第一个没有看明白`setChecked([{id:'1'},{id:'1-0'}])`只有两个参数为什么会选中1,1-0,1-1三个
第二个的意思是给的数据是一维pId的形式，转换成多维数组的形式吗

**Comment by wzfxue** [comment]
`/**
 * json格式转树状结构
 * @param {json} json数据
 * @param {String} id的字符串
 * @param {String} 父id的字符串
 * @param {String} children的字符串
 * @return {Array} 数组
 */
function arrayToTree(data, id, pid,childrenName) 
{
    if(!childrenName){
        childrenName='children';
    }
    if (!data || !data.length) return [];
    var targetData = [];                    //存储数据的容器(返回)
    var records = {};
    var itemLength = data.length;           //数据集合的个数
    for (var i = 0; i < itemLength; i++)
    {
        var o = data[i];
        records[o[id]] = o;
    }
    for (var i = 0; i < itemLength; i++)
    {
        var currentData = data[i];
        var parentData = records[currentData[pid]];
        if (!parentData)
        {
            targetData.push(currentData);
            continue;
        }
        parentData[childrenName] = parentData[childrenName] || [];
        parentData[childrenName].push(currentData);
    }
    return targetData;
}`
上面这段代码可以转换。
第一个是因为级联原因，父节点勾选之后会自动将所有子节点同时勾选。设想将checkStrictly这个参数作为方法级。在setChecked的时候使这种级联关系失效

**Comment by hsiangleev** [comment]
@wzfxue 那这样的话，我如果选中父节点，和部分子节点，那父节点是应该半选还是全选，
如果是半选的话，那就不选中父节点，只选中部分子节点不就好了，
但如果是全选的话，已经设置了checkStrictly参数为false，父节点选中，子节点没有全部选中是不是不太合理

**Comment by wzfxue** [comment]
![image](https://user-images.githubusercontent.com/19793076/56938956-dc01f580-6b37-11e9-8a74-34436d7fefff.png)

el.setChecked([10,11],true) 之后江苏省下的全部节点都被选中。

**Comment by hsiangleev** [comment]
@wzfxue 对啊，设置的是江苏省被选中，那它下面的所有节点肯定都被选中了，如果不想被选中，可以设置checkStrictly为true，不太明白你想表达的意思

**Comment by wzfxue** [comment]
当设置checkStrictly为true的时候，如果想用到这种级联特性的话就不行了。
我的意思是仅仅当调用setChecked的时候可以选择性的临时将checkStrictly设置为true。方法执行完毕之后checkStrictly设置回原来的值，这仅仅是一个小建议。

**Comment by hsiangleev** [comment]
@wzfxue 目前还没有这种打算，因为本身默认的checkStrictly没设置true，就是级联的，如果再临时性的使用应该会给人误导的感觉吧
