### ISSUE TITLE
eletree能否在执行右键新增时用户输入node名称

### ISSUE THREAD

**Issue by EliuGit** [hsiangleev/layuiExtend#41]
你好，eletree现在的添加node的逻辑感觉有点怪，以往的操作流程  点击新增->让用户输入名称->ajax到后台->成功返回新添加的信息->完成添加

**Comment by weathon** [comment]
这个我做我的项目时完成了，过几天发pr

**Comment by hsiangleev** [comment]
@EliuGit 谢谢你的建议，功能现在已经添加

**Comment by weathon** [comment]
@hsiangleev 那就不用我发PR了？

**Comment by hsiangleev** [comment]
@EliuGit 如果功能相似的话，可以不用发了
