### ISSUE TITLE
nodeContextmenu在第二次绑定时被off 掉了,导致事件无法触法

### ISSUE THREAD

**Issue by EliuGit** [hsiangleev/layuiExtend#43]
如题

**Comment by hsiangleev** [comment]
@EliuGit 你说的第二次绑定是什么意思，怎么使用的

**Comment by EliuGit** [comment]
932行 和 1114行 就是nodeContextmenu事件无法触法

**Comment by hsiangleev** [comment]
@EliuGit 意思是如果你开启了右键菜单的话就不触发右键事件了，因为右键菜单开启之后应该就不需要右键事件了吧

**Comment by EliuGit** [comment]
有可能有哟跟据菜单node的数据决定显示那些菜单项

**Comment by hsiangleev** [comment]
@EliuGit 目前没有根据不同节点显示不同菜单的功能
