### ISSUE TITLE
空树不能直接添加结点吗？

### ISSUE THREAD

**Issue by wenxiayili** [hsiangleev/layuiExtend#44]
您的append(key, data)中的key是必须的，如果我使用js（不是您的api）添加数据，而此时是空树（没有任何结点的树），这个方法就不能使用了

**Comment by hsiangleev** [comment]
@wenxiayili 谢谢你的反馈，append方法增加一种使用方式，不传key，或者直接传key为null或者为空的话，则直接添加到根节点
```javascript
el3.append({
    id: 300,
    label: "烈山区",
    checked: true,
    disabled: true
})
```

**Comment by wenxiayili** [comment]
thank you ! @hsiangleev
