### ISSUE TITLE
后台返回数据不管是否存在checked:true树都会被选中

### ISSUE THREAD

**Issue by sulanyou** [hsiangleev/layuiExtend#45]
后台返回的数据中，没有被选中的数据是没有cheched:true的但是树中显示的还是被选中的。
![1LK_~D9H`BR34DQ2$3E K`L](https://user-images.githubusercontent.com/38974097/57345679-4e00bd00-717e-11e9-8ec0-7714640a8aae.png)

**Comment by hsiangleev** [comment]
@sulanyou 那父节点有没有设置选中，如果父节点被选中，因为默认的是父子关联的，所以子节点会被选中

**Comment by sulanyou** [comment]
> @sulanyou那父节点有没有设置选中，如果父节点被选中，因为默认的是父子关联的，所以子节点会被选中

没有，红圈中的4条数据都是没有被选中状态的，如果是正常的话应该是这样显示，实际却是全部被选中了
![~G4@ZHUX 0ZJEHTKMYDY_E1](https://user-images.githubusercontent.com/38974097/57347402-be124180-7184-11e9-9ece-de0aa8e487d7.png)

**Comment by hsiangleev** [comment]
@sulanyou 那你实际是哪几条设置了选中，系统设置有没有设置选中

**Comment by sulanyou** [comment]
> @sulanyou 那你实际是哪几条设置了选中，系统设置有没有设置选中

除了角色管理和其字节点没有设置选中外其他的都有设置为选中

**Comment by hsiangleev** [comment]
@sulanyou 角色管理是系统设置的子节点，如果系统设置被选中了，肯定所有的都被选中啊，你把系统设置取消选中试试

**Comment by sulanyou** [comment]
> @sulanyou 角色管理是系统设置的子节点，如果系统设置被选中了，肯定所有的都被选中啊，你把系统设置取消选中试试

把系统设置取消选中的确可以，但是我只想关掉角色管理及其子节点，其他的都选中。

**Comment by hsiangleev** [comment]
@sulanyou 那这样的话就只能设置父子不关联了，设置checkStrictly:true

**Comment by sulanyou** [comment]
> @sulanyou 那这样的话就只能设置父子不关联了，设置checkStrictly:true

这样设置地区可以，但能不能设置为选中某个节点的时候其所有父节点跟着一起选中，但是其子节点不选中。

**Comment by hsiangleev** [comment]
@sulanyou 目前没有这种，现在是要么父节点被选中，则所有子孙节点全部被选中，要么就是父子无关，你说的这种，**选中某个节点的时候其所有父节点跟着一起选中，但是其子节点不选中**，感觉会很乱吧

**Comment by sulanyou** [comment]
> @sulanyou 目前没有这种，现在是要么父节点被选中，则所有子孙节点全部被选中，要么就是父子无关，你说的这种，**选中某个节点的时候其所有父节点跟着一起选中，但是其子节点不选中**，感觉会很乱吧

不会啊，就像我做的这个功能一样，我不想然某个角色有 《角色管理》 这个菜单的权限，按照eleTree开启父子关系的情况下是做不到的

**Comment by sulanyou** [comment]
> > @sulanyou 目前没有这种，现在是要么父节点被选中，则所有子孙节点全部被选中，要么就是父子无关，你说的这种，**选中某个节点的时候其所有父节点跟着一起选中，但是其子节点不选中**，感觉会很乱吧
> 
> 不会啊，就像我做的这个功能一样，我不想让某个角色有 《角色管理》 这个菜单的权限，按照eleTree开启父子关系的情况下是做不到的

**Comment by hsiangleev** [comment]
@sulanyou 那你这种不应该选中最外层的那个系统设置吧，只需要选中需要菜单管理和用户管理不就可以了吗，而且你给系统设置选中，按你的意思应该是系统设置那个就该是全选了，而不是半选的状态了吧

**Comment by sulanyou** [comment]
> @sulanyou那你这种不应该选中最外层的那个系统设置吧，只需要选中需要菜单管理和用户管理不就可以了吗，而且你给系统设置选中，按你的意思应该是系统设置那个就该是全选了，而不是半选的状态了吧

因为我这个树是用来管理后台管理系统的菜单的，只想把角色管理及其子节点关闭而已，其他的都是选中，就像图片里面，只想把角色管理这个给取消掉，其他的系统管理，用户管理什么的都要显示。
![E_{GK4I)MY3%)EYXB5~TFKJ](https://user-images.githubusercontent.com/38974097/57354806-15bda680-719f-11e9-8a11-8c6292095110.png)

**Comment by sulanyou** [comment]
> @sulanyou那你这种不应该选中最外层的那个系统设置吧，只需要选中需要菜单管理和用户管理不就可以了吗，而且你给系统设置选中，按你的意思应该是系统设置那个就该是全选了，而不是半选的状态了吧

因为我看别人用的Jquery zTree是可以半选中的，而eleTree目前应该是没有半选中的功能，看以后能不能关系吧，谢谢我的回答了。
![W@Z5%R6H81VS3{(C}@`7(OM](https://user-images.githubusercontent.com/38974097/57354920-70ef9900-719f-11e9-85ff-524999e7e2e9.png)

**Comment by hsiangleev** [comment]
@sulanyou 不好意思，目前没有设置半选节点的方法，只是通过子节点的选中状态来判断父节点是不是半选的，你的这种需求应该是可以用父子不关联来实现吧

**Comment by sulanyou** [comment]
> @sulanyou 不好意思，目前没有设置半选节点的方法，只是通过子节点的选中状态来判断父节点是不是半选的，你的这种需求应该是可以用父子不关联来实现吧

父子不关联是可以实现的，只是不完美，因为选中子节点的时候没有把父节点一起选中。我刚刚看了一下eleTree在选中的时候是可以半选的，只是当数据回显的时候无法显示半选数据，直接显示全选了，

比如这张图片在选中的时候可以半选
![) )0{90$)`}ML@5M10JLQ7O](https://user-images.githubusercontent.com/38974097/57355781-659d6d00-71a1-11e9-953a-3932e5ef009a.png)
如何点击保存后再次回显数据就变成这个样子了
![) )0{90$)`}ML@5M10JLQ7O](https://user-images.githubusercontent.com/38974097/57355827-7fd74b00-71a1-11e9-8092-aab6e0cb26fa.png)

**Comment by sulanyou** [comment]
> @sulanyou 不好意思，目前没有设置半选节点的方法，只是通过子节点的选中状态来判断父节点是不是半选的，你的这种需求应该是可以用父子不关联来实现吧

这张图片是保存后回显的数据就被全部选中了
![) )0{90$)`}ML@5M10JLQ7O](https://user-images.githubusercontent.com/38974097/57355923-bad97e80-71a1-11e9-975f-331e87cdd50c.png)

**Comment by hsiangleev** [comment]
@sulanyou 第一张图是因为你点击了一下用户管理，取消了他的选中，每次更新选中状态时，系统会根据子节点的选中来决定父节点是否半选还是全选，第二张图是因为一开始初始化的时候最外层节点就被选中了，所以系统会自动把所有的子节点全部选中

**Comment by sulanyou** [comment]
> @sulanyou 第一张图是因为你点击了一下用户管理，取消了他的选中，每次更新选中状态时，系统会根据子节点的选中来决定父节点是否半选还是全选，第二张图是因为一开始初始化的时候最外层节点就被选中了，所以系统会自动把所有的子节点全部选中

建议增加 渲染数据的时候父节点被选中不要把子节点也一起选中了，谢谢。
