### ISSUE TITLE
搜索内容为空时，会出现多条文本提示

### ISSUE THREAD

**Issue by ruiifly** [hsiangleev/layuiExtend#46]
![image](https://user-images.githubusercontent.com/45475882/57842765-be9f7d80-77ff-11e9-90f0-252146e80710.png)

**Comment by hsiangleev** [comment]
@ruiifly 谢谢提醒，已经改了

**Comment by hsiangleev** [comment]
@ruiifly 上次没注意到，不能直接用html，不然会把所有的节点都删除了，即第一次未搜索到，然后第二次搜索到之后所有的节点都没了

**Comment by weathon** [comment]
> 然后第二次搜索到之后所有的节点都没了
Hahahaha
