### ISSUE TITLE
请问导入模块后样式出不来是什么原因

### ISSUE THREAD

**Issue by HuayangZhao** [hsiangleev/layuiExtend#51]
大佬，谢谢
![{0B848D71-974A-4AFE-8D27-05F2CCA6E619}_20190525112111](https://user-images.githubusercontent.com/44315235/58363979-97bc0800-7edf-11e9-95b8-a6b2825a4454.jpg)
页面是这样的。。。
![{3389D9E2-6476-4285-A366-E562C2E29076}_20190525112441](https://user-images.githubusercontent.com/44315235/58363994-c20dc580-7edf-11e9-945b-530099ffebde.jpg)

**Comment by HuayangZhao** [comment]
我放在form外面和里面都是这样的。。。

**Comment by hsiangleev** [comment]
@HuayangZhao eleTree.css样式有没有引入，在eleTree文件夹下面

**Comment by HuayangZhao** [comment]
感谢大佬
