### ISSUE TITLE
下拉树首次加载怎么设置指定项高亮

### ISSUE THREAD

**Issue by zhangjianzhi1989** [hsiangleev/layuiExtend#58]
下拉树首次加载怎么设置指定项高亮（不带checkbox）

新手，见谅！

**Comment by hsiangleev** [comment]
@zhangjianzhi1989 这个可以自己用选择器实现，例如`$(".eleTree [data-id='3'] .eleTree-node-content").addClass("eleTree-node-content-active")`

**Comment by zhangjianzhi1989** [comment]
@hsiangleev  好的，感谢回复。
