### ISSUE TITLE
删除节点时在回调函数中获取所有节点json无效

### ISSUE THREAD

**Issue by weathon** [hsiangleev/layuiExtend#60]
删除节点时在回调函数中获取所有节点json还是原来的

**Comment by hsiangleev** [comment]
@weathon 获取所有节点是用的getAllNodeData方法吗，因为删除节点之后可能会调用stop方法阻止删除节点，所以这个时候数据还没有删除，不能直接获取所有节点，可以在回调里面使用异步删除的方式，例如
```javascript
setTimeout(function() {
  d.async()
  console.log(el3.getAllNodeData())
},0)  
```

**Comment by weathon** [comment]
我获取所有节点的方法是我加上去的，但没有关系了，效果基本一样。setTimeout 0ms就可以了吗？
