### ISSUE TITLE
eltree append 方法一次添加了两个节点

### ISSUE THREAD

**Issue by sckjzk** [hsiangleev/layuiExtend#65]
el.append(pKey, data);
第二个节点没有Id
![QQ截图20190717102107](https://user-images.githubusercontent.com/10610966/61342406-a211d700-a87c-11e9-9519-d5b8ac2c6d42.png)

第二个节点数据如下图
![2](https://user-images.githubusercontent.com/10610966/61342476-da191a00-a87c-11e9-9b5c-0f67ae2da9b4.png)

找到问题了，我是自定义的key，但是html中还是data-id 所以取不到数据
![3](https://user-images.githubusercontent.com/10610966/61349265-10af5e80-a896-11e9-8b86-acbab1930034.png)

@

**Comment by hsiangleev** [comment]
@sckjzk 不是太明白你的意思，那个key可以在request参数里面设置

**Comment by sckjzk** [comment]
@hsiangleev 
![QQ图片20190820154938](https://user-images.githubusercontent.com/10610966/63328136-2cf55e00-c362-11e9-9042-e93583ef49a2.png)
自定义的key是Id,但是生成的代码还是data-id

**Comment by hsiangleev** [comment]
@sckjzk 这个肯定不能直接用自定义名字作为属性名，这样可能会重写默认属性，比如id，class之类的，用自定义data属性也是一样的

**Comment by sckjzk** [comment]
上面那样取就有问题，要修改
if (data[options.request.key] == $(item).data("id")) {
            isExist = true;
 }

**Comment by hsiangleev** [comment]
@sckjzk 你的这个应该是自定义属性大小写问题，这个在7.29版本已经修改过了，这个问题是自定义属性大写时，需要把大写字母转中划线，比如appId转成app-id就正常了

**Comment by sckjzk** [comment]
好滴，谢谢
