### ISSUE TITLE
changeOnSelect和value一块使用时，自动弹出下级，能否初始化的时候不弹出？

### ISSUE THREAD

**Issue by mozhuwanjieDEV** [hsiangleev/layuiExtend#68]
如下代码，会自动弹出下拉框，实际上只是初始化的时候需要默认选中一个
`   var cas=cascader({
                elem: "#a",
                data: [
                {
                    value: 'A',
                    label: 'a',
					changeOnSelect: true,
                    children: [
                        {
                            value: 'AA1',
                            label: 'aa1',
                        }
                    ]
                },{
                    value: 'B',
                    label: 'b',
					changeOnSelect: true,
                    children: [
                        {
                            value: 'BB1',
                            label: 'bb1',
                        }
                    ]
                }
            ],
                // url: "/aa",
                // type: "post",
                // triggerType: "change",
                 showLastLevels: false,
                // where: {
                //     a: "aaa"
                // },
                value: ['A'],
                changeOnSelect: true,
                success: function (valData,labelData) {
                    console.log(valData,labelData);
                }
            });

`

**Comment by mozhuwanjieDEV** [comment]
更正一下，应该是设置默认值value，如果不是最后一个级别，就会弹出；
实际上很多情况可能是初始化的时候需要显示一个默认值

**Comment by hsiangleev** [comment]
@mozhuwanjieDEV 谢谢反馈，已经修改了

**Comment by mozhuwanjieDEV** [comment]
感谢

**Comment by mozhuwanjieDEV** [comment]
更新后使用changeOnSelect:true，第二级别（一直到倒数第二级别）点击后会显示上一级别和当前级别的名字，点击最后级别则无问题

**Comment by hsiangleev** [comment]
@mozhuwanjieDEV 没有明白你的意思，我测试的好像没什么问题，，，

**Comment by mozhuwanjieDEV** [comment]
showLastLevels: true时，
比如数据级别是全省/A/a1/aa2
点击a1时，显示的是/A/a1
点击aa2时，显示的是aa2

**Comment by hsiangleev** [comment]
@mozhuwanjieDEV 这种条件是showLastLevels和changeOnSelect同时设置为true才会出现的，但是他们两个应该是互斥的关系，一个是只显示叶子节点，一个是可以选择非叶子节点，所以不应该会同时设置为true吧

**Comment by mozhuwanjieDEV** [comment]
> @mozhuwanjieDEV 这种条件是showLastLevels和changeOnSelect同时设置为true才会出现的，但是他们两个应该是互斥的关系，一个是只显示叶子节点，一个是可以选择非叶子节点，所以不应该会同时设置为true吧

会的，比如四级地市，/A/a1/aa2/aa3，选择中间的地级市aa2，结果只显示aa2也是有需求的，
showLastLevels觉得可以改为点击哪一级别就显示哪一级别，这样也包含只显示最后一级

**Comment by hsiangleev** [comment]
@mozhuwanjieDEV 好的，第157行修改为
`this.textStr=this.option.showLastLevels ? this.textArr[this.textArr.length-1] : this.textArr.join("/");`，
即如果两个字段同时为true，就只显示当前点的的那一个
