### ISSUE TITLE
cascader中显示的值和value值都是label的值

### ISSUE THREAD

**Issue by mozhuwanjieDEV** [hsiangleev/layuiExtend#73]
cascader中显示的值和value值都是label的值，
一般的选择框都有一个显示值和一个value值，目前选中后获取的value值是label，应该是value的值才对吧？
比如示例中的，选中a/bb1后获取到的是a/bb1，期望是A/BB1

layui.$("#a").val()

"a/bb1"

**Comment by hsiangleev** [comment]
@mozhuwanjieDEV 参数有一个success回调函数，每次选中都会调用这个函数，里面有两个参数数组，对应的就是显示值和value值

**Comment by mozhuwanjieDEV** [comment]
@hsiangleev  已经使用success回调函数赋值变量解决，多谢
