### ISSUE TITLE
cascader   Uncaught TypeError: this.domContent.off is not a function

### ISSUE THREAD

**Issue by wangmax0330** [hsiangleev/layuiExtend#74]
Uncaught TypeError: this.domContent.off is not a function
我是这样的,在列表页点击弹出编辑框,弹出编辑框后要请求后端获取路径,赋值到Cascader
<img width="753" alt="111" src="https://user-images.githubusercontent.com/7903596/63992347-ff58a380-cb1d-11e9-80ce-c5f04a2978d1.png">

<img width="834" alt="WX20190830-115941@2x" src="https://user-images.githubusercontent.com/7903596/63992294-bc96cb80-cb1d-11e9-8635-a62d4d455b1f.png">

**Comment by wangmax0330** [comment]
出现这个问题的原因是什么呢?

**Comment by wangmax0330** [comment]
我加了个判断,然后就不报错了,不晓得这个 this.domContent.off()是做什么处理的
`
 reload: function (option) {
            var self = this;
            if (this.domContent != undefined&&this.domContent !='') {
                this.domContent.off();
            }
`

**Comment by hsiangleev** [comment]
@wangmax0330 domContent是整个下拉框的dom容器，因为reload是把之前的那个销毁，然后重写render，容器上面的事件需要取消，不然事件就会定义多次，你这个错误我没有重现出来，你的这个代码应该也不是最新的吧，你先用最新的代码试下
