### ISSUE TITLE
提几个小建议

### ISSUE THREAD

**Issue by DongXu1234** [hsiangleev/layuiExtend#8]
1.如果开启懒加载后（不知道不开启是不是这样），新增节点时，新节点不应该有子节点
在新增节点的方法中，大概三百多行改为，var obj = {label: value, isLeaf : true, }
2.开启懒加载后，在节点未打开时， 直接使用add方法的话， 不会将后台已经存在的该节点的子节点加载， 所以应该先将子节点全部加载出来之后在添加子节点。

**Comment by DongXu1234** [comment]
3.不知道是不是我使用reload的姿势有问题，
eleTree.reload("#tree", {where: {data: JSON.stringify(data.data)}})
这段代码好像并没有将我从后台获取的结果渲染到前端，
然后如果有结果的作者能否告知发送到qq:2924394519或者17625649074的微信，万分感谢

**Comment by DongXu1234** [comment]
更新一下现在使用reload的方法，直接使用render函数，不知道会不会有影响, 目前未发现。

**Comment by yuanrui** [comment]
借此再提一个小建议，能否支持自定义右键菜单。

**Comment by hsiangleev** [comment]
@DongXu1234 感谢您的建议，这几天没登github，没看到，以前写的那个确实有点乱，最近又重新写了，文档基本模仿elementUI，已经提交上来了

**Comment by DongXu1234** [comment]
> @DongXu1234 感谢您的建议，这几天没登github，没看到，以前写的那个确实有点乱，最近又重新写了，文档基本模仿elementUI，已经提交上来了
好像没有在文档里面看到关于在insert data之前或者之后处理数据的方法， 因为大部分时候需要在后台操作一部分数据然后在前台新添加节点中，比如id或者一些其他的属性。如果作者有时间的话，建议搞一搞，或者我有时间的情况下看能不能update一下

**Comment by hsiangleev** [comment]
@DongXu1234 如果使用右键菜单添加的话，有触发事件
![eleTree](https://raw.githubusercontent.com/hsiangleev/layuiExtend/master/images/eleTree-4.png)
也可以自定义的方式通过 el.append(key,data) 方法添加
