### ISSUE TITLE
遇到过这个情况吗？

### ISSUE THREAD

**Issue by GONETHEN** [hsiangleev/layuiExtend#9]
![test](https://s1.ax1x.com/2018/12/05/FllyDO.png)

这种情况是怎么一回事？有人遇到过吗？

**Comment by hsiangleev** [comment]
@GONETHEN 目前没遇到，是加载完之后就出现的吗

**Comment by GONETHEN** [comment]
> @GONETHEN 目前没遇到，是加载完之后就出现的吗

是的，我把它放到了弹出层里，新增和编辑打开的是同一个弹出层，但是新增按钮就不会增加，编辑按钮每点击一次就会加一个。。。

**Comment by hsiangleev** [comment]
@GONETHEN 我在弹窗打开，然后编辑也没问题，
![eleTree](https://raw.githubusercontent.com/hsiangleev/layuiExtend/master/images/eleTree-5.png)
而且我也没有定义过 layui-unselect样式，也没有追加过这个节点，能再具体描述一下触发这个问题的方式吗？还有控制台有没有报错

**Comment by hsiangleev** [comment]
@GONETHEN 你这个应该是最后form.render()了，不需要再执行这个操作了，这个checkbox是我内部自定义的，没有使用layui的form模块，因为这个有三种状态，layui的只有两种，所以把form.render()去掉应该就可以了

**Comment by hsiangleev** [comment]
@GONETHEN 或者不要把树放到 .layui-form这个类里面

**Comment by GONETHEN** [comment]
> @GONETHEN 你这个应该是最后form.render()了，不需要再执行这个操作了，这个checkbox是我内部自定义的，没有使用layui的form模块，因为这个有三种状态，layui的只有两种，所以把form.render()去掉应该就可以了

@hsiangleev 找到问题所在了
```
form.val('addRoleForm', {
                        'name': data.name
                        ,'roleType': data.roleType
                    });
```

因为这些代码可能会重新渲染layui-form里的东西
